version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    container_name: mongo_cv_match
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo_data:
